### ISSUE TITLE
To Contributors

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#112]
@Hulen, @whwlsfb , @a-w11 , @Mugahedb , @JeromeFa , @yutthaphon , @wizard872 , @kostefun , @RemboIII , @molokal , @lostprophet , @foxhnd , @fidodone , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @SadPencil , @yuk7 , @kix99aug , @naruepanart , @dustofsoul , @kazihorka , @holao09 
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

**Comment by Stanly5** [comment]
@yutthaphon , @wizard872 , @molokal , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @yuk7 , @kix99aug , @naruepanart , @holao09
- REMINDER -
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

**Comment by Stanly5** [comment]
@yutthaphon , @wizard872 , @molokal , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @yuk7 , @kix99aug , @naruepanart , @holao09

REMINDER -
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

**Comment by Stanly5** [comment]
@wizard872 , @molokal , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @kix99aug ,  @holao09 , @gabrig11 , @ilkmon 

REMINDER -
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

**Comment by yutthaphon** [comment]
Hi, 
I'm send 2 mails to you about 5-6 month ago, but not hove any reply.
https://i.imgsir.com/3aLO.png

**Comment by Stanly5** [comment]
@yutthaphon,
I'm very sorry for that. I checked you sent email, but I should figure out why reply has not been sent.
I will get back soon.

**Comment by Stanly5** [comment]
@yutthaphon ,
Reply was sent, so if you didn't get it, please let me know.
Thank you.

**Comment by yutthaphon** [comment]
@Stanly5 I received an email from you. And I will continue to support you as a Thai translator.
Thank you very much.
