### ISSUE TITLE
Can't link with https

### ISSUE THREAD

**Issue by unruliness** [RaiDrive/RaiDrive.Translation#138]
I can connect to my WebDav powered by synology via http
but when i connect via https , alert me “由于意外的数据包格式，握手失败”
how can i fix this?

**Comment by Stanly5** [comment]
Hello @unruliness ,

RaiDrive engineering team doesn't see this github page, so please leave this message on RaiDrive community page; https://with.raidrive.com/ to get quick and detail response about it.
I'm sorry for this inconvenience.

Thank you and have a good day~
