### ISSUE TITLE
about "Bucket" and "Tenant" in v1.9.0

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#140]
Hello @ilkmon , @kazihorka 

Bucket and Tenant are technical nouns, so it may be better to use English as is when there is no proper terminology in translation. But please see below page for understanding it. I could not follow this technical words. ^^;;
- Bucket: https://docs.aws.amazon.com/en_pv/AmazonS3/latest/dev/UsingBucket.html (use in AWS, Google)
- Tenant: https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-create-new-tenant (use in Azure)

**Comment by ilkmon** [comment]
@Stanly5

I've reviewed the documentations.
I've reviewed official Turkish documentations about Tenant and I've observed that "tenant" is used as kiracı(like renter) and definition of this word in the dictionary is also kiracı. There is no Turkish documentation about bucket at both firm.
In my opinion, those words are technical words, and they are using in English in my country, also all over the world. I'll leave them English. But if the team can add an info button near them, we can add Turkish means and also explanations inside it.
