### ISSUE TITLE
New lines for v.1.9.0 (coming soon)

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#141]
@Hulen , @whwlsfb , @a-w11 , @Mugahedb , @JeromeFa , @yutthaphon @wizard872 , @kostefun , @RemboIII , @molokal , @lostprophet , @foxhnd , @fidodone , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @SadPencil , @yuk7 , @kix99aug , @naruepanart , @dustofsoul , @kazihorka , @holao09 , @Abu3safeer , @gabrig11 , @ilkmon 

Hello Contributors,

Version 1.9.0 is coming soon, and 19 lines are added newly on it.
All the StringDictionary files are updated and if you have a chance to review and translate it, then it should be greatly appreciated.
Thank you so much for your interesting for RaiDrive always and have a great day.

**Comment by Abu3safeer** [comment]
Working on it.

**Comment by Stanly5** [comment]
@kostefun ,
On next time we would prepare the beta version, but right now beta version is not ready at this time.
Please kindly understand it.
