### ISSUE TITLE
Issue when copying file to OneDrive Business

### ISSUE THREAD

**Issue by FredLaffitte** [RaiDrive/RaiDrive.Translation#153]
When I try to upload a file to my one drive business account, I receive this error:

>> https://prnt.sc/pvljyr

Please help me to fix.
[https://prnt.sc/pvljyr](url)

**Comment by Stanly5** [comment]
@FredLaffitte 
Raidrive/Translation in Github is only for the translation of RaiDrive.
To get fast support, please leave a message in RaiDrive website, https://with.raidrive.com  so that proper support team can know about it. I'm sorry for this.
Thanks a lot.
