### ISSUE TITLE
Identical (OneDrive) files displayed in Windows Explorer after rename

### ISSUE THREAD

**Issue by RemboIII** [RaiDrive/RaiDrive.Translation#154]
When I rename a file in Windows Explorer, a second file seems to be created with the new name. After refreshing, 2 identical files are displayed.
When I look online at the OneDrive location (mobile app or webpage), there's only 1 file. 
I'm unable to remove 1 instance of the doubly displayed files. 

![Identical files displayed in online (Onedrive) folder 02](https://user-images.githubusercontent.com/42135158/68660851-3eea3580-053a-11ea-85fe-800dfba812c3.png)

**Comment by Stanly5** [comment]
@RemboIII 
Raidrive/Translation in Github is only for the translation of RaiDrive.
To get fast supporting, please leave a message in RaiDrive website, https://with.raidrive.com  so that proper support team can know about it. I'm sorry for this.
Thanks a lot.
