### ISSUE TITLE
Add more lines for v1.9.0 (coming soon)

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#155]
@Hulen , @whwlsfb , @a-w11 , @Mugahedb , @JeromeFa , @yutthaphon @wizard872 , @kostefun , @RemboIII , @molokal , @lostprophet , @foxhnd , @fidodone , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @SadPencil , @yuk7 , @kix99aug , @naruepanart , @dustofsoul , @kazihorka , @holao09 , @Abu3safeer , @gabrig11 , @ilkmon, @LordDamionDevil 

Hello Contributors,

Version 1.9.0 is coming soon, and 4 more lines are added newly at the tail of the file from the last v1.9.0 update which is 19 lines added on it.
All the StringDictionary files are updated and if you have a chance to review and translate it, then it should be greatly appreciated.

<system:String x:Key="Settings.RegisterToStartup">Register to Startup</system:String>
<system:String x:Key="AddDrive.MountAtStart">Reconnect at program start</system:String>
<system:String x:Key="AddDrive.MountAtSignIn">Reconnect at sign-in</system:String>
<system:String x:Key="AddDrive.MountAtBoot">Reconnect at boot</system:String>

These are simple explanation for each line.

- Register to Startup : add Raidrive to Windows Startup
- Reconnect at program start : automatically reconnect storage when RaiDrive is started
- Reconnect at sign-in : automatically reconnect storage when Windows logon
- Reconnect at boot : automatically reconnect storage when system boot

Thank you so much for your interesting for RaiDrive always and have a great day.

**Comment by kazihorka** [comment]
@Stanly5 Hi Stanly, in CZ these lines are missing, or I'm just blind 😆 ?

**Comment by Stanly5** [comment]
@kazihorka 
I'm sorry that. You are not blind 😆.
There was something should be changed, so file upload was delayed.
I will get back to you when everything is ready.
Sorry again, and on next time I will post after everything is settle down.

**Comment by kix99aug** [comment]
What's the difference between key "Settings.General.RunAtBoot" and key "Settings.RegisterToStartup" ?

**Comment by SadPencil** [comment]
In my opinion,
RegisterToStartup ---- make a shortcut to Start Menu\Startup; will be executed when someone login to the Windows
RunAtBoot ---- when Windows is powered on. No need to login to Windows
MountAtSignIn ---- when someone login to the Windows

I don't know if I understand correctly.

**Comment by kix99aug** [comment]
> In my opinion,
> RegisterToStartup ---- make a shortcut to Start Menu\Startup; will be executed when someone login to the Windows
> RunAtBoot ---- when Windows is powered on. No need to login to Windows
> MountAtSignIn ---- when someone login to the Windows
> 
> I don't know if I understand correctly.

It seems like that Raidrive uses the Windows Registry to set startup process.
That's why I don't understand the difference between that two keys.
![Windows Registry](https://user-images.githubusercontent.com/10905628/68940020-0918ab80-07dd-11ea-9397-b126eae46319.png)

**Comment by Stanly5** [comment]
@kix99aug , @SadPencil 

Key "Settings.General.RunAtBoot" will not be used in v1.9.0.
It is replaced to key "Settings.RegisterToStartup", but for the other purpose Settings.General.RunAtBoot key is remained.
Please refer to below picture.
![image](https://user-images.githubusercontent.com/39616295/68940313-2736d980-07e6-11ea-8cf1-106c8ce7f83d.png)
Thank you~

**Comment by Stanly5** [comment]
@kix99aug
Did you send email to support@raidrive.com to confirm your email?

As I already  posted we prepared small gift for contributors.

REMINDER -
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

**Comment by ilkmon** [comment]
Planning to work on at next weekend. :)

**Comment by kix99aug** [comment]
> @kix99aug
> Did you send email to [support@raidrive.com](mailto:support@raidrive.com) to confirm your email?
> 
> As I already posted we prepared small gift for contributors.
> 
> REMINDER -
> Hello Contributors!
> We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "[support@raidrive.com](mailto:support@raidrive.com)" an email with your email address, and your github ID, and then we will let you know the details again by email.
> Thank you so much, and please keep seeing our improvement!
> Have a great day!

I've sent emails twice, but I didn't get any reply.

**Comment by Stanly5** [comment]
@kix99aug 
I will check that, and then get back to you. I'm sorry for this missing. ^^

**Comment by Stanly5** [comment]
@ilkmon 
Thank you so much for your contribution always!
I hope I get updates on next weekend. ^^

**Comment by Stanly5** [comment]
@kix99aug 
We checked your email and will send email shortly.
I'm sorry again, and have a great day~

**Comment by kix99aug** [comment]
> @kix99aug
> We checked your email and will send email shortly.
> I'm sorry again, and have a great day~

I've received the mail, thanks.
