### ISSUE TITLE
RaiDrive in ARM win10 X86

### ISSUE THREAD

**Issue by hametan** [RaiDrive/RaiDrive.Translation#166]
RaiDrive in ARM win10 X86 ,Con't run.

**Comment by Stanly5** [comment]
Hello @hametan 
RaiDrive/Translation in Github is only for the translation work, so technical team likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com

Thank you.
Have a nice day~
