### ISSUE TITLE
Indonesia

### ISSUE THREAD

**Issue by alif72** [RaiDrive/RaiDrive.Translation#168]
I would like to help with the translation into Indonesia.

**Comment by Stanly5** [comment]
@alif72
Thank you so much for your contribution! It was merged.
Please keep watching our improvement and help us updating.

We have a contributor campaign for your efforts with a small gift, so please so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.

Thank you so much!
