### ISSUE TITLE
添加谷歌云盘总是失败添加谷歌云盘总是失败

### ISSUE THREAD

**Issue by liveskai** [RaiDrive/RaiDrive.Translation#170]
添加谷歌云盘总是失败

**Comment by Stanly5** [comment]
Hello @liveskai 
RaiDrive/Translation in Github is only for the translation work, so technical team likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day~
