### ISSUE TITLE
Portuguese

### ISSUE THREAD

**Issue by jcmarchi** [RaiDrive/RaiDrive.Translation#19]
I would love to help with the translations for Portuguese and Spanish. 

May I also suggest, for the Portuguese language, to have two distinctive files: "Brazilian Portuguese" (PT-BR) and "Portuguese" (PT) itself. Despite the same language, technical terms are translated much differently in between both variations, having Brazilian Portuguese keeping most of the technical terms partially in English, while many other terms are translated to unique words or terms.

For the process, can you describe how to use the translation files? Where should I save them? I didn't find much info in the config file... Should I simply place the files in the application folder?

Thanks.

**Comment by Stanly5** [comment]
Thank you so much for your interest and suggestion. I will initialize two different StringDictionary files for PT and PT-BR as your suggestion.
For the process, current version of RaiDrive could not be applied these language files, so it cannot be confirmed on RaiDrive right now. I will update you after releasing beta version which can load the language file.
