### ISSUE TITLE
RaiDrive installed in some random language

### ISSUE THREAD

**Issue by Jekabs123** [RaiDrive/RaiDrive.Translation#193]
I just installed RaiDrive but it didn't install in English but some random language I don't even understand.

**Comment by Stanly5** [comment]
@Jekabs123 
If you are asking how to change the language in RaiDrive App, then you can choose the language in here.
![image](https://user-images.githubusercontent.com/39616295/78991584-3858fc00-7b74-11ea-9fcc-8bd1a7c72737.png)
like this.
![image](https://user-images.githubusercontent.com/39616295/78991633-53c40700-7b74-11ea-96d8-977b43a713bb.png)

If you need other technical support, then please leave message in https://with.raidrive.com.
Thank you.

**Comment by Spown** [comment]
can also confirm. I've chosen eng in the installer, but the program runs in German, since it's my system locale. not a big deal, but still annoying.
