### ISSUE TITLE
RaiDrive using a lot of RAM

### ISSUE THREAD

**Issue by ZeJackOfSpades** [RaiDrive/RaiDrive.Translation#195]
I have a problem when using RaiDrive. The RAM used by RaiDrive is insane, it increase over and over. 
![image](https://user-images.githubusercontent.com/25030199/86455827-7bfd7500-bd21-11ea-9eb2-8da1f90595ee.png)

Version : 2020.6.25

**Comment by Stanly5** [comment]
Hello @ZeJackOfSpades ,
RaiDrive/Translation in Github is only for the translation work, so technical team likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day~
