### ISSUE TITLE
NEW lines for v2020.9 (coming soon)

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#204]
@Hulen , @whwlsfb , @a-w11 , @Mugahedb , @JeromeFa , @yutthaphon @wizard872 , @kostefun , @RemboIII , @molokal , @lostprophet , @foxhnd , @fidodone , @Kasukoi , @Highdeger , @michal78 , @GrandMasterX3 , @SadPencil , @yuk7 , @kix99aug , @naruepanart , @dustofsoul , @kazihorka , @holao09 , @Abu3safeer , @gabrig11 , @ilkmon, @LordDamionDevil, @alif72, @DoryanR, @Wolf-Wind , @Paultje52 , @SQLtattoo

Hello Contributors,

Version 2020.9 will be released soon, and several lines will be added newly at the tail of each language file.
Please help us to get translation for these.

	
	<system:String x:Key="Words.FileExplorer">File Explorer</system:String>
	<system:String x:Key="FileExplorer.AutoRefresh">Update storage changes asynchronously</system:String>
	<system:String x:Key="FileExplorer.ModifiedDate">Try to keep &quot;Date modified&quot; when copying</system:String>
	<system:String x:Key="FileExplorer.FilesystemWatcher">Monitor process access to files</system:String>
	<system:String x:Key="FileExplorer.PerformanceExtension">Quick Copy/Move/Delete for remote storage</system:String>
	<system:String x:Key="FileExplorer.PerformanceExtension.Overwrite">Overwrite target</system:String>
	<system:String x:Key="FileExplorer.PerformanceExtension.Rename">Rename source</system:String>
	<system:String x:Key="Words.Skip">Skip</system:String>
	<system:String x:Key="Words.Slow">Slow</system:String>
	<system:String x:Key="Message.ResponseSlow">A response may be slow</system:String>
	<system:String x:Key="Words.AdvancedOptions">Advanced Options</system:String>
	<system:String x:Key="Words.Properties">Properties</system:String>
	<system:String x:Key="Words.MySubscription">My Subscription</system:String>
	<system:String x:Key="Words.ShareWithOther">Share with others</system:String>
	<system:String x:Key="Words.SharedWithMe">Shared with me</system:String>
	<system:String x:Key="Words.Import">Import</system:String>
	<system:String x:Key="Words.Export">Export</system:String>
	<system:String x:Key="Words.ProcessMonitor">Process Monitor</system:String>
	<system:String x:Key="Account.Endpoint">Endpoint</system:String>
	<system:String x:Key="GoogleDrive.SharedDrives">Shared drives</system:String>
	<system:String x:Key="Words.Reading">Reading</system:String>
	<system:String x:Key="Words.Writing">Writing</system:String>
	<system:String x:Key="Words.Hide">Hide</system:String>

For your better understanding, please see these.

![raidrivetranslation202009_01](https://user-images.githubusercontent.com/39616295/91438717-c248fd80-e8a6-11ea-9e37-1ebadd57259f.png)

![raidrivetranslation202009_02](https://user-images.githubusercontent.com/39616295/91438742-cffe8300-e8a6-11ea-9197-33e2abeb58cc.png)

![raidrivetranslation202009_03](https://user-images.githubusercontent.com/39616295/91438781-e3115300-e8a6-11ea-931e-f2528f433c7e.png)

**Comment by Abu3safeer** [comment]
Thank you for the pictures, they are big help for better understanding.

**Comment by Abu3safeer** [comment]
Done #205

**Comment by whwlsfb** [comment]
zh-Hans done. #207

**Comment by SadPencil** [comment]
> 
> 
> zh-Hans done. #207

https://github.com/RaiDrive/RaiDrive.Translation/pull/209
