### ISSUE TITLE
Captive portal support

### ISSUE THREAD

**Issue by xmha97** [RaiDrive/RaiDrive.Translation#214]
To work I have to connect to WiFi Starbucks daily and I see this error every time I turn on the computer :(
Please support captive portal...
![image](https://user-images.githubusercontent.com/23485114/93322371-7b588300-f828-11ea-89d6-59e6164e4375.png)

**Comment by Stanly5** [comment]
Hello @xmha97 

RaiDrive/Translation in Github is only for the translation work, so technical team mosr likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day

**Comment by xmha97** [comment]
I can't create account on https://with.raidrive.com

**Comment by Stanly5** [comment]
If so, please send email to support@raidrive.com

**Comment by xmha97** [comment]
OK, Thanks.
