### ISSUE TITLE
Terrible copying speed, even after updated to professional editon

### ISSUE THREAD

**Issue by rextang008** [RaiDrive/RaiDrive.Translation#219]
Terrible copy speed, even after updated to professional editon, even slower than onedrive itself, hope the developer could do some improving.

Standard edtion: 300k/second

Professinal edition: 300K/second (no change, even tickle the extention for speed up)

Onedrive original: 1.2 M/second
(Doesn't want to use onedrive as everytime kill my hards drive (it synchronize automatically, my laptop only 500 G hard disk, but my onedrive is 5T, so I give up and use Raidrive, however Raidrive transfering speed for local file to cloud kills me(speed is too slow). Hope the developer could do some change about this transfering speed.
My Raidrive account: rog****mo@outlook.com

**Comment by Stanly5** [comment]
Hello @rextang008 

RaiDrive/Translation in Github is only for the translation work, so technical team most likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day
