### ISSUE TITLE
Name bug with google shared drive

### ISSUE THREAD

**Issue by Akior** [RaiDrive/RaiDrive.Translation#222]
I have a name bug issue or cache issue

how to represent:

1. create a google team drive folder with file a b c
2. mount with raidrive
3. move files to another team drive folder, wait 120 second and copy all files back (use another soft, not raidrive)
4. see that you have a b c original name in cache, and a(1) b(1) c(1) files that copyed new
5. try to open original file - they disappear as doens't exist
6. open new a(1) file, and its work well
7. remount shared disk, and you see a b c file, that's opened well and seems new.

**Comment by Stanly5** [comment]
Hello @Akior 

I'm sorry for the delay. RaiDrive/Translation in Github is only for the translation work, so technical team most likely cannot see your message. Please leave a message again in RaiDrive page https://with.raidrive.com to get quick supports.

Thank you.
Have a nice day

**Comment by Akior** [comment]
thank you!
