### ISSUE TITLE
Dubox unit

### ISSUE THREAD

**Issue by LeninZapata** [RaiDrive/RaiDrive.Translation#227]
Hello, you can add as a unit to the "Dubox" service, it is a service store that many people are using and it is seen that it is very light. I hope they put it on their roadmap

**Comment by Stanly5** [comment]
Hello @LeninZapata 

RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day
