### ISSUE TITLE
File not found after right-click to any file

### ISSUE THREAD

**Issue by lht99** [RaiDrive/RaiDrive.Translation#228]
When I open the file by double-click then the file will open fine.
When I tried to right-click to do something, the file will disappear then appear again but we can not open file after appearing again.

**Comment by Stanly5** [comment]
Hello @lht99 

RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day
