### ISSUE TITLE
[401 unauthorization] - hope support utf-8 encode

### ISSUE THREAD

**Issue by qq1014853731** [RaiDrive/RaiDrive.Translation#229]
Employees of our company need to use RaiDrive to connect to NAS server, but our user name is not in English, because changing the user name will cause a lot of problems,so we hope RaiDrive can convert user name to UTF-8 encode

I'm very sure this is the reason for '401 authorization failed'

**Comment by Stanly5** [comment]
Hello @qq1014853731 

RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com
Thank you.
Have a nice day
