### ISSUE TITLE
Unable to activate account

### ISSUE THREAD

**Issue by github-h** [RaiDrive/RaiDrive.Translation#238]
I'm sorry to ask this question in issue.

When I registered my account, I didn't click the activation email in time, and the activation link was invalid.
So I can't activate, I can't re register, I can't change my password.
Please help me to solve this problem. Thank you. I hope you can provide the option to resend your email

I've given it to you support@raidrive.com I sent an email, but there was no response.

**Comment by Stanly5** [comment]
Hello @github-h 

I'm sorry that you didn't get no response from support@raidrive.com. However could you please input this question on https://with.raidrive.com again? It will be the best way to get quick responses and supports

Thank you, and have a nice day

**Comment by github-h** [comment]
I tried it https://with.raidrive.com To ask my question. 

But I don't know how to send a new question, I click reply, the page will automatically jump to the home page. 

So I gave up. Please help me solve this problem, I really don't know how to send a new problem.

**Comment by Stanly5** [comment]
Please try like this.
1. Sign in on www.raidrive.com. "Sign in" is on the right upper.
2. Select menu "Support/Global Forum"
3. You can find "+ New Topic"

If you have any question, please send me a message again.
Thank you.

**Comment by github-h** [comment]
I'm looking for you just because I can't log in. I hope you can send me activation email again.

Then you said that you need to log in for forum topics, I can't log in.

I'm going to tell you again support@raidrive.com Sent a request to resend the account activation email

**Comment by Stanly5** [comment]
Sorry for inconvenience, I'm not a responsible person, and I cannot see support@raidrive.com.
I will convey your messages, and try to check for responding to you.
