### ISSUE TITLE
How should I report security vulnerability

### ISSUE THREAD

**Issue by ycdxsb** [RaiDrive/RaiDrive.Translation#240]
Hello,
     I found a security vulnerability in RaiDrive. How should I report it to your team? I only found the Forum on the official website but I think it's not good to report a security vulnerability in the forum.

**Comment by Stanly5** [comment]
Hello @ycdxsb 
Thank you for the supporting. Please send an email to "support@raidrive.com" to talk with technical team.

**Comment by ycdxsb** [comment]
Thanks.
