### ISSUE TITLE
Confirmation that the email is genuine

### ISSUE THREAD

**Issue by Kai-Z-JP** [RaiDrive/RaiDrive.Translation#261]
I received an email a few days ago that looks like this, was this sent by you?
If so, in the next preview, for security reasons, could you please place the attachment link to the file on the RaiDrive site, not on the Google Drive one?
![image](https://user-images.githubusercontent.com/42648535/156911462-bf686d22-db9f-496e-9d09-40f4f9419e79.png)

**Comment by Stanly5** [comment]
@Kai-Z-JP 
Yes, I sent that email. I understood your concerns about security reasons. I will discuss with team and apply it on next time.
Thank you
