### ISSUE TITLE
这软件不支持连接smb嘛，需要将网络硬盘转换成本地硬盘显示

### ISSUE THREAD

**Issue by 1265578519** [RaiDrive/RaiDrive.Translation#265]
这软件不支持连接smb嘛，需要将网络硬盘转换成本地硬盘显示
![image](https://user-images.githubusercontent.com/6442439/160002522-3d756c3d-e7ac-4ff7-93f2-748363e4314d.png)

**Comment by Hulen** [comment]
@1265578519 這邊是翻譯專用的專案，它們不會回應這類問題。都要直接向技術團隊https://with.raidrive.com/去留言。

另外，您的問題就在畫面左邊的 "模擬本地磁盤" 就是你要的功能，但那是 Pro 訂閱才能使用。

**Comment by 1265578519** [comment]
> @1265578519 這邊是翻譯專用的專案，它們不會回應這類問題。都要直接向技術團隊 https://with.raidrive.com/ 去留言。
> 
> 另外，您的問題就在畫面左邊的 "模擬本地磁盤" 就是你要的功能，但那是 Pro 訂閱才能使用。

好的，nas需要用smb协议去连接，看到软件还不支持，这就去那边留言
