### ISSUE TITLE
2022.6.41 BUG REPORT

### ISSUE THREAD

**Issue by shoufu12324** [RaiDrive/RaiDrive.Translation#279]
There may be a bug in 2022.6.41. After connecting to SFTP and specifying the connection path, the content in the file server cannot be displayed correctly, and it is displayed as an empty folder. The problem is solved after replacing the old version.
To contact: wangsong12324@outlook.com

**Comment by Stanly5** [comment]
Hello @shoufu12324 

RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Thank you.
Have a nice day
