### ISSUE TITLE
It cant work in windows11 22H1

### ISSUE THREAD

**Issue by LikeGhost** [RaiDrive/RaiDrive.Translation#281]

**Comment by Stanly5** [comment]
@LikeGhost 
Hello,
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Thank you.
Have a nice day

**Comment by LikeGhost** [comment]
> @LikeGhost Hello, RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports. https://with.raidrive.com/ Thank you. Have a nice day



> @LikeGhost Hello, RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message. Please leave a message again in RaiDrive page to get quick supports. https://with.raidrive.com/ Thank you. Have a nice day


But how  can I leave a message in RaiDrive page, I cant find the button to leave  a message.
Maybe you can take a photo for me?

Thank you anyway!

**Comment by Stanly5** [comment]
@LikeGhost 
After sign in on https://www.raidrive.com, you can find "+ New Topic" on with.raidrive.com, and you can leave messages.
Or you can send email to support@raidrive.com to get  helps.
Thank you.

**Comment by LikeGhost** [comment]
> @LikeGhost After sign in on https://www.raidrive.com, you can find "+ New Topic" on with.raidrive.com, and you can leave messages. Or you can send email to [support@raidrive.com](mailto:support@raidrive.com) to get helps. Thank you.

Ok,I see it.

Thank you again!
