### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by izhangguapi** [RaiDrive/RaiDrive.Translation#283]
![1](https://user-images.githubusercontent.com/33612298/195039763-218fbd7a-753a-4bf0-b011-490da344d5df.png)

我不知道为什么会出现这样的问题，网上没有找到解决方案

**Comment by Hulen** [comment]
@izhangguapi  這邊是翻譯專用的專案，它們不會回應這類問題。都要直接向技術團隊 https://with.raidrive.com/ 去留言。
