### ISSUE TITLE
apologies but why do I have to reconnect everything on startup

### ISSUE THREAD

**Issue by afraidoflight** [RaiDrive/RaiDrive.Translation#290]
apologies but why do I have to manually reconnect everything on startup? [i have win10 pro]...I cannot find any genuinely helpful info on how to use Raidrive [I have been using it off and on foŕyears but this issue always comes up no matter if google, onedrive, et al; i always have to manually set Raiddrive up all over again everytime i reboot my pc...and i am using 7 different drives- googles, ms, mega, box]

*apologies if i am not formatting this correctly i like github but only recently started being really active on it

**Comment by Stanly5** [comment]
@afraidoflight 
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message.
Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Or email to [support@raidrive.com](mailto:support@raidrive.com)
Thank you!
