### ISSUE TITLE
通过alist开启蓝奏云网盘的webdav服务，用raidrive载入，无法对文件进行操作

### ISSUE THREAD

**Issue by yz-qc** [RaiDrive/RaiDrive.Translation#291]
通过alist开启蓝奏云网盘的webdav服务，用raidrive载入，无法对文件进行操作，只能看到文件列表，其他操作都不行，如：
     1、复制文件到本地磁盘
     2、新建文件
     3、删除文件
     4、修改文件内容
     5、重命名文件等
     都不行，有时候还会卡死
     尝试提交过alist的issues，alist作者给的回复是raidrive，原话是：
     1、 `raidrive上传文件需要预先创建空占位文件，所以：对于所有不支持上传空文件的存储均无法上传。显然 蓝奏云就属于其中一种。`
     2、 `蓝奏云的直链对ua有特定要求 对于一些ua它还会经过一个网页跳转，所以raidirve可能完全不支持蓝奏云。`

**Comment by Stanly5** [comment]
@yz-qc 
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message.
Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Or email to [support@raidrive.com](mailto:support@raidrive.com)
Thank you!
