### ISSUE TITLE
使用sftp挂载到电脑中，直接用vscode挂载盘里创建项目，npm失败，文件格式都是sftp

### ISSUE THREAD

**Issue by lingGuanX** [RaiDrive/RaiDrive.Translation#294]
**### 以下是 npm install --save-dev electron 错误日志：**
2119 warn my-electron-app@1.0.0 No description
2120 warn my-electron-app@1.0.0 No repository field.
2121 verbose stack Error: electron@23.1.3 postinstall: `node install.js`
2121 verbose stack Exit status 1
2121 verbose stack     at EventEmitter.<anonymous> (C:\Users\20828\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
2121 verbose stack     at EventEmitter.emit (node:events:513:28)
2121 verbose stack     at ChildProcess.<anonymous> (C:\Users\20828\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2121 verbose stack     at ChildProcess.emit (node:events:513:28)
2121 verbose stack     at maybeClose (node:internal/child_process:1100:16)
2121 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2122 verbose pkgid electron@23.1.3
2123 verbose cwd Y:\dozenith\workspace\electron\my-electron-app
2124 verbose Windows_NT 10.0.19044
2125 verbose argv "D:\\nodejs\\node.exe" "C:\\Users\\20828\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron"
2126 verbose node v16.18.0
2127 verbose npm  v6.14.15
2128 error code ELIFECYCLE
2129 error errno 1
2130 error electron@23.1.3 postinstall: `node install.js`
2130 error Exit status 1
2131 error Failed at the electron@23.1.3 postinstall script.
2131 error This is probably not a problem with npm. There is likely additional logging output above.
2132 verbose exit [ 1, true ]

**### 以下是 cnpm install --save-dev electron 错误日志：**
PS Y:\dozenith\workspace\electron\my-electron-app> cnpm install --save-dev electron
× Install fail! Error: EISDIR: illegal operation on a directory, symlink 'Y:\dozenith\workspace\electron\my-electron-app\node_modules\.store\ms@2.1.2\node_modules\ms' -> 'Y:\dozenith\workspace\electron\my-electron-app\node_modules\.store\debug@4.3.4\node_modules\ms'
Error: EISDIR: illegal operation on a directory, symlink 'Y:\dozenith\workspace\electron\my-electron-app\node_modules\.store\ms@2.1.2\node_modules\ms' -> 'Y:\dozenith\workspace\electron\my-electron-app\node_modules\.store\debug@4.3.4\node_modules\ms'
npminstall version: 7.5.2
npminstall argv: D:\nodejs\node.exe C:\Users\20828\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\20828\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com --save-dev electron

**Comment by Hulen** [comment]
@lingGuanX 這邊是翻譯專用的專案，它們不會回應這類問題。

要直接到技術團隊 https://with.raidrive.com/ 論壇留言，或是 E-mail 到 support@raidrive.com 去諮詢。

**Comment by lingGuanX** [comment]
> @lingGuanX 這邊是翻譯專用的專案，它們不會回應這類問題。
> 
> 要直接到技術團隊 https://with.raidrive.com/ 論壇留言，或是 E-mail 到 [support@raidrive.com](mailto:support@raidrive.com) 去諮詢。

好的谢谢你
