### ISSUE TITLE
intresting on base of what it's created

### ISSUE THREAD

**Issue by mzayarnyuk** [RaiDrive/RaiDrive.Translation#295]
is carotdive use same base src ?
if use raidrive it upload always full file to onedrive for eample or use md5 small blocks and submit only modified parts to work faster and use less trafic to upload ????

**Comment by Stanly5** [comment]
@mzayarnyuk 
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message.
Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Or email to [support@raidrive.com](mailto:support@raidrive.com)
Thank you!
