### ISSUE TITLE
fail to install the latest version 2023-02-22

### ISSUE THREAD

**Issue by KristineWatson** [RaiDrive/RaiDrive.Translation#296]
![图片](https://user-images.githubusercontent.com/92555979/224814318-b92e3ad0-25b7-49e1-a4eb-27195732c6f3.png)

**Comment by Stanly5** [comment]
@KristineWatson 
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message.
Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Or email to [support@raidrive.com](mailto:support@raidrive.com)
Thank you!
