### ISSUE TITLE
Temporary file（start with ~$）remains when xlsx file closed

### ISSUE THREAD

**Issue by almes10** [RaiDrive/RaiDrive.Translation#297]
I'm using Raidrive to maintain Microsoft Teams Channel Files in local.
In usual when we open a xlsx file a ~$ file will be generated, it means that file is in open.
If I open xlsx file with Microsoft Excel the temporary file will be disappear when I close the file.
But if I open it with WPS spreadsheet the temporary file remains even I closed the file.
WPS spreadsheet  is much friendlier than Excel for me, so if can fix this issue I'll sincerely thanks for that.
<img width="548" alt="Snipaste_2023-03-17_13-43-12" src="https://user-images.githubusercontent.com/48024116/225822381-3fc9c7e1-7d78-487a-82f8-c786b80b1185.png">

**Comment by Stanly5** [comment]
@almes10 
RaiDrive/Translation in Github is only for the translation work, so technical team doesn't see your message.
Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/
Or email to [support@raidrive.com](mailto:support@raidrive.com)
Thank you!
