### ISSUE TITLE
raidrive使用webdav有什么办法禁用磁盘缓存吗？读取文件的时候，会生成一份文件，天天空间已满

### ISSUE THREAD

**Issue by 1265578519** [RaiDrive/RaiDrive.Translation#298]
C:\ProgramData\OpenBoxLab\RaiDrive\Cache
![image](https://user-images.githubusercontent.com/6442439/230137131-8878a304-85da-46ae-a3d9-5885ef8fb762.png)
设置10秒就是，读取线程断开10秒后，才会删除缓存文件，设置0秒就是立即删除。
如果原始文件有200G，他就会在C盘生成一个200G的文件直到磁盘用尽发生读取错误，因为我C盘根本没有200G

设置0秒不是禁用缓存，只是读取完成后立即删除缓存，目前也没有最大上限值能控制。

**Comment by Hulen** [comment]
@1265578519 這邊是翻譯專用的專案，它們不會回應這類問題。

要直接到技術團隊 https://with.raidrive.com/ 論壇留言，或是 E-mail 到 support@raidrive.com 去諮詢。
