### ISSUE TITLE
Can't paste access key id and secret access key

### ISSUE THREAD

**Issue by fitzer200** [RaiDrive/RaiDrive.Translation#300]
Its red in those boxes. Don't want to type the secret access key out, I would surely type something wrong

**Comment by OpenBoxLab** [comment]
Hello @fitzer200,

RaiDrive/Translation in Github is only for the translation work, so technical team likely cannot see your message. Please leave a message again in RaiDrive page to get quick support.
https://with.raidrive.com/

Thank you.
Have a nice day~
