### ISSUE TITLE
SOS help,OneDrive Read-only cannot be cancelled and uploaded

### ISSUE THREAD

**Issue by nmccx** [RaiDrive/RaiDrive.Translation#92]
SOS求助，遇到大麻烦，OneDrive 只读不能取消，无法上传文件，怎么办 
SOS help, encounter big trouble, OneDrive read-only can not be cancelled, can not upload files, how to do
![QQ五笔ddd截图未命名](https://user-images.githubusercontent.com/49706604/56261846-1bc7e680-610f-11e9-9dd7-2923439e8e50.png)

It's no use setting up this problem. Thank you.

From: Baidu Translation

**Comment by Stanly5** [comment]
以下是GaiHub的RaiDrive / Translation的翻译版仅供参考。 很难确定适当的人来回答您的询问。
请再次在RaiDrive网页上留言。
https://www.raidrive.com/contact/

Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day

**Comment by nmccx** [comment]
已解决谢谢，我发现停止One Drive可以取消只读
Thank you. I found that stopping One Drive can cancel read-only.

**Comment by tanst** [comment]
新版本准备收费了 ，已弃

**Comment by tanst** [comment]
> 以下是GaiHub的RaiDrive / Translation的翻译版仅供参考。 很难确定适当的人来回答您的询问。
> 请再次在RaiDrive网页上留言。
> https://www.raidrive.com/contact/
> 
> Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
> Please leave this message again on RaiDrive webpage.
> https://www.raidrive.com/contact/
> 
> Thank you~
> Have a great day

What does "Professional Feature" mean?

**Comment by Sanchopance** [comment]
Everything is working, there were some minor problems.
