### ISSUE TITLE
A permanent change on dirve icon

### ISSUE THREAD

**Issue by lpchroc** [RaiDrive/RaiDrive.Translation#94]
After ever assigning one drive letter (e.g. E) to a cloud disk through RaiDriver, the icon of this dirve was permanently changed to the RaiDirver icon and couldn't be restored after reassignment, even by getting rid of all icon cache.
![Picture](https://user-images.githubusercontent.com/49260802/56465603-a8ec9300-63ce-11e9-8282-72b05466b971.png)

**Comment by Stanly5** [comment]
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~

**Comment by SadPencil** [comment]
@lpchroc, The drive's custom icon is usually controlled at registry
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\DriveIcons`
If there are some keys, delete them.

**Comment by bersbersbers** [comment]
Also check
```
HKEY_CLASSES_ROOT\Applications\Explorer.exe
```

I (with an extra R: drive icon) had a subkey `Drives\R\DefaultIcon` there with value `"C:\Program Files\OpenBoxLab\RaiDrive\RaiDrive.exe",2` (even after uninstalling RaiDrive). Deleting that fixed the issue for me without a reboot.

**Comment by QiuMone** [comment]
> Also check
> 
> ```
> HKEY_CLASSES_ROOT\Applications\Explorer.exe
> ```
> 
> I (with an extra R: drive icon) had a subkey `Drives\R\DefaultIcon` there with value `"C:\Program Files\OpenBoxLab\RaiDrive\RaiDrive.exe",2` (even after uninstalling RaiDrive). Deleting that fixed the issue for me without a reboot.

thank you very much😁
