### ISSUE TITLE
Released Version 1.6.X

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/RaiDrive.Translation#95]
Version 1.6.X was released and it is ready to move professional version.
Therefore some lines are added for new feature, and we are pleased to get contributor's and your helps again. 
Added are below 7 lines and we are greatly appreciated if you help us to translate for each language xaml files.

	
	<system:String x:Key="Settings.General.UseDriveIcon">Use the custom icon on a connected drive</system:String>
	<system:String x:Key="AddDrive.LocalDisk">Local Disk</system:String>
	<system:String x:Key="AddDrive.FileLock">File Lock</system:String>
	<system:String x:Key="AddDrive.WritableDrive">Writable Drive</system:String>
	<system:String x:Key="ToolTip.LocalDisk">Mount like a local disk</system:String>
	<system:String x:Key="ToolTip.FileLock">WebDAV File Lock</system:String>
	<system:String x:Key="ToolTip.FileLock2">depends on WebDAV server</system:String>

**Comment by Stanly5** [comment]
Hi contributors~
Released new version has 7 added lines for professional features. Could you please help us for translating?
At the tail of xaml files, these 7 lines are added. Please review the uploaded language string xaml file.


<system:String x:Key="Settings.General.UseDriveIcon">Use the custom icon on a connected drive</system:String>
<system:String x:Key="AddDrive.LocalDisk">Local Disk</system:String>
<system:String x:Key="AddDrive.FileLock">File Lock</system:String>
<system:String x:Key="AddDrive.WritableDrive">Writable Drive</system:String>
<system:String x:Key="ToolTip.LocalDisk">Mount like a local disk</system:String>
<system:String x:Key="ToolTip.FileLock">WebDAV File Lock</system:String>
<system:String x:Key="ToolTip.FileLock2">depends on WebDAV server</system:String>

@Hulen , @JeromeFa , @whwlsfb , @a-w11 , @Mugahedb , @kazihorka , @SadPencil , @holao09 , @wizard872, @yuk7 , @foxhnd , @dustofsoul , @lostprophet , @molokal , @fidodone , @kostefun , @RemboIII , @yutthaphon , @Kasukoi , @Stanly5 , @OpenBoxLab

**Comment by SadPencil** [comment]
> Use the custom icon on a connected drive

The word 'custom' usually means the user can modify it. But it seems that when this feature is turned on, the icon is RaiDrive's icon; and when this feature is turned off, the icon is the network drive icon.
So the word 'custom' might be improper, or if I misunderstood.

**Comment by dustofsoul** [comment]
maybe change it to"Use system default icon"in next version.it will be less misunderstanding
> 
> 
> > Use the custom icon on a connected drive
> 
> The word 'custom' usually means the user can modify it. But it seems that when this feature is turned on, the icon is RaiDrive's icon; and when this feature is turned off, the icon is the network drive icon.
> So the word 'custom' might be improper, or if I misunderstood.

**Comment by Stanly5** [comment]
@SadPencil , @dustofsoul 
About the option "Use the custom icon on a connected drive",
Checked : Use stored setting either RaiDrive default icon or replaced icon by user if did.
Unchecked : not controlled by RaiDrive, System default.

Therefore checked this option means custom icon correctly if user already modified icon.
